print ("*"*5, "Kredit Keaktifan Mahasiswa", "*"*5)
print ("Student Activities Credit")
print ("1. Menambahkan kegiatan")
print ("2. Menampilkan Jumlah Poin")
print ("3. Keluar")
print ("-"*28)
int(input("Silahkan masukan pilihan yang Anda: "))
pilihan = int(input("Nama Kegiatan: "))
if pilihan == 1:
    int(input("HMTI 2022"))
    int(input("iaa 2022"))
    int(input("FAITH Petra 2022"))
    int(input("Webinar UI/UX"))
print("Nama kegiatan")