Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
import turtle
turtle.showturtle()
turtle.bgcolor('pink')
turtle.forward(90)
turtle.undo()
turtle.pencolor('yellow')
turtle.forward(90)
turtle.left(45)
turtle.forward(20)
turtle.left(45)
turtle.forward(120)
turtle.left(45)
turtle.forward(20)
turtle.left(45)
turtle.forward(180)
turtle.left(45)
turtle.forward(20)
turtle.left(45)
turtle.forward(120)
turtle.left(45)
turtle.forward(20)
turtle.left(45)
turtle.forward(90)
turtle.bgcolor('yellow')
turtle.undo()
turtle.bgcolor('pink')
turtle.forward(90)
turtle.right(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(15)
turtle.left(90)
turtle.pencolor('brown')
turtle.forward(50)
turtle.left(90)
turtle.forward(15)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(15)
turtle.left(90)
turtle.forward(50)
turtle.goto(90,120)
turtle.undo()
turtle.circle(360)
turtle.undo(
)
SyntaxError: unmatched ')'
turtle.undo()
turtle.pendown(90,120)
Traceback (most recent call last):
  File "<pyshell#47>", line 1, in <module>
    turtle.pendown(90,120)
TypeError: pendown() takes 0 positional arguments but 2 were given
turtle.pendown()
turtle.circle(90)
turtle.undo()
turtle.goto(0,45)
turtle.cirle(40)
Traceback (most recent call last):
  File "<pyshell#52>", line 1, in <module>
    turtle.cirle(40)
AttributeError: module 'turtle' has no attribute 'cirle'. Did you mean: 'circle'?
turtle.right(90)
turtle.circle(45)
